apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.name }} running on AWS EKS cluster
  annotations:
    github.com/project-slug: chitta-behera/eks-cluster-workflow
spec:
  type: service
  lifecycle: experimental
  owner: user:chitta
